extern const GeoLayout another_door_geo[];
extern Lights1 another_door_f3d_material_005_lights;
extern Lights1 another_door_handle_lights;
extern u8 another_door_wood_ci4[];
extern u8 another_door_wood_ci4_pal_rgba16[];
extern Vtx another_door_Cube_012_mesh_layer_1_vtx_0[64];
extern Gfx another_door_Cube_012_mesh_layer_1_tri_0[];
extern Vtx another_door_Cube_012_mesh_layer_1_vtx_1[104];
extern Gfx another_door_Cube_012_mesh_layer_1_tri_1[];
extern Gfx mat_another_door_f3d_material_005[];
extern Gfx mat_revert_another_door_f3d_material_005[];
extern Gfx mat_another_door_handle[];
extern Gfx another_door_Cube_012_mesh_layer_1[];
extern Gfx another_door_material_revert_render_settings[];
