extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern const GeoLayout ccm_area_2_geo[];
extern const GeoLayout ccm_area_2[];
extern const Collision ccm_area_2_collision[];
extern const MacroObject ccm_area_2_macro_objs[];
extern Lights1 ccm_dl_f3d_material_lights;
extern Lights1 ccm_dl_f3d_material_001_lights;
extern Lights1 ccm_dl_f3d_material_003_lights;
extern Lights1 ccm_dl_f3d_material_002_lights;
extern Vtx ccm_dl_Cube_mesh_layer_1_vtx_0[308];
extern Gfx ccm_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_mesh_layer_1_vtx_1[4];
extern Gfx ccm_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_Cube_001_mesh_layer_1_vtx_0[308];
extern Gfx ccm_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_001_mesh_layer_1_vtx_1[4];
extern Gfx ccm_dl_Cube_001_mesh_layer_1_tri_1[];
extern Gfx mat_ccm_dl_f3d_material[];
extern Gfx mat_ccm_dl_f3d_material_001[];
extern Gfx mat_ccm_dl_f3d_material_003[];
extern Gfx mat_ccm_dl_f3d_material_002[];
extern Gfx ccm_dl_Cube_mesh_layer_1[];
extern Gfx ccm_dl_Cube_001_mesh_layer_1[];
extern Gfx ccm_dl_material_revert_render_settings[];
