#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"

#include "mist/geo.inc.c"
#include "explosion/geo.inc.c"
#include "butterfly/geo.inc.c"
#include "coin/geo.inc.c"
#include "warp_pipe/geo.inc.c"
#include "door/geo.inc.c"
#include "bowser_key/geo.inc.c"
#include "flame/geo.inc.c"
#include "blue_fish/geo.inc.c"
#include "leaves/geo.inc.c"
#include "mario_cap/geo.inc.c"
#include "number/geo.inc.c"
#include "mushroom_1up/geo.inc.c"
#include "star/geo.inc.c"
#include "dirt/geo.inc.c"
#include "transparent_star/geo.inc.c"
#include "white_particle/geo.inc.c"
#include "wooden_signpost/geo.inc.c"
#include "tree/geo.inc.c"

#include "luigi_rope/geo.inc.c"
#include "bomb/geo.inc.c"

#include "fridge/geo.inc.c"

#include "nightmare_chunk/geo.inc.c"
#include "arrow_platform/geo.inc.c"

#include "mario_puppet/geo.inc.c"
#include "bombable_door/geo.inc.c"

#include "impact_smoke/geo.inc.c"
#include "bowser_flame/geo.inc.c"

#include "cutscene_bowser/geo.inc.c"
#include "disguised_toad/geo.inc.c"
#include "peach_cage/geo.inc.c"
#include "talkable_goomba/geo.inc.c"

#include "talkable_luigi/geo.inc.c"
#include "temp_earthwake_block/geo.inc.c"
#include "earthwake_hand/geo.inc.c"
#include "earthwake_head/geo.inc.c"
#include "earthwake_foot/geo.inc.c"

#include "big_massif/geo.inc.c"
#include "lil_massif/geo.inc.c"
#include "penny/geo.inc.c"
#include "earthwake_left_hand/geo.inc.c"
#include "earthwake_right_hand/geo.inc.c"
#include "earthwake_left_foot/geo.inc.c"
#include "earthwake_right_foot/geo.inc.c"
#include "earthwake_block_blue/geo.inc.c"
#include "earthwake_block_pink/geo.inc.c"
#include "earthwake_block_green/geo.inc.c"
#include "earthwake_block_yellow/geo.inc.c"
#include "earthwake_left_shoulder/geo.inc.c"
#include "earthwake_right_shoulder/geo.inc.c"

#include "earthwake_new_head/geo.inc.c"
#include "paper_cube/geo.inc.c"
#include "bowling_pin/geo.inc.c"
#include "big_bombable_door/geo.inc.c"
#include "peasant_mario/geo.inc.c"
#include "peasant_peach/geo.inc.c"
#include "peasant_bowser/geo.inc.c"
#include "baljeet/geo.inc.c"
#include "candace/geo.inc.c"