extern const GeoLayout hmc_area_1_geo[];
extern const GeoLayout hmc_area_1[];
extern const Collision hmc_area_1_collision[];
extern const MacroObject hmc_area_1_macro_objs[];
extern Lights1 hmc_dl_wall_lights;
extern Lights1 hmc_dl_floor_lights;
extern Lights1 hmc_dl_f3d_material_003_lights;
extern Lights1 hmc_dl_f3d_material_002_lights;
extern u8 hmc_dl_walls_i8[];
extern u8 hmc_dl_floor_i8[];
extern u8 hmc_dl__0_ci4[];
extern u8 hmc_dl__0_ci4_pal_rgba16[];
extern Vtx hmc_dl_Cube_001_mesh_layer_1_vtx_0[134];
extern Gfx hmc_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_Cube_001_mesh_layer_1_vtx_1[48];
extern Gfx hmc_dl_Cube_001_mesh_layer_1_tri_1[];
extern Vtx hmc_dl_Cube_001_mesh_layer_1_vtx_2[22];
extern Gfx hmc_dl_Cube_001_mesh_layer_1_tri_2[];
extern Vtx hmc_dl_Cube_001_mesh_layer_1_vtx_3[4];
extern Gfx hmc_dl_Cube_001_mesh_layer_1_tri_3[];
extern Gfx mat_hmc_dl_wall[];
extern Gfx mat_hmc_dl_floor[];
extern Gfx mat_hmc_dl_f3d_material_003[];
extern Gfx mat_hmc_dl_f3d_material_002[];
extern Gfx mat_revert_hmc_dl_f3d_material_002[];
extern Gfx hmc_dl_Cube_001_mesh_layer_1[];
extern Gfx hmc_dl_material_revert_render_settings[];
