extern const GeoLayout talkable_goomba_geo[];
extern Lights1 talkable_goomba_foot_lights;
extern Lights1 talkable_goomba_head_lights;
extern Lights1 talkable_goomba_body_lights;
extern u8 talkable_goomba_head_ci8[];
extern u8 talkable_goomba_head_ci8_pal_rgba16[];
extern Vtx talkable_goomba_goomba_mesh_layer_1_vtx_0[175];
extern Gfx talkable_goomba_goomba_mesh_layer_1_tri_0[];
extern Vtx talkable_goomba_goomba_mesh_layer_1_vtx_1[90];
extern Gfx talkable_goomba_goomba_mesh_layer_1_tri_1[];
extern Vtx talkable_goomba_goomba_mesh_layer_1_vtx_2[240];
extern Gfx talkable_goomba_goomba_mesh_layer_1_tri_2[];
extern Gfx mat_talkable_goomba_foot[];
extern Gfx mat_talkable_goomba_head[];
extern Gfx mat_revert_talkable_goomba_head[];
extern Gfx mat_talkable_goomba_body[];
extern Gfx talkable_goomba_goomba_mesh_layer_1[];
extern Gfx talkable_goomba_material_revert_render_settings[];
