extern const GeoLayout earthwake_block_pink_geo[];
extern Lights1 earthwake_block_pink_border_lights;
extern Lights1 earthwake_block_pink_pinkwall_lights;
extern u8 earthwake_block_pink_PinkWall_ci4[];
extern u8 earthwake_block_pink_PinkWall_ci4_pal_rgba16[];
extern Vtx earthwake_block_pink_PinkCube_mesh_layer_1_vtx_0[168];
extern Gfx earthwake_block_pink_PinkCube_mesh_layer_1_tri_0[];
extern Vtx earthwake_block_pink_PinkCube_mesh_layer_1_vtx_1[24];
extern Gfx earthwake_block_pink_PinkCube_mesh_layer_1_tri_1[];
extern Gfx mat_earthwake_block_pink_border[];
extern Gfx mat_earthwake_block_pink_pinkwall[];
extern Gfx mat_revert_earthwake_block_pink_pinkwall[];
extern Gfx earthwake_block_pink_PinkCube_mesh_layer_1[];
extern Gfx earthwake_block_pink_material_revert_render_settings[];
