extern const GeoLayout wf_area_3_geo[];
extern const GeoLayout wf_area_3[];
extern const Collision wf_area_3_collision[];
extern const MacroObject wf_area_3_macro_objs[];
extern const GeoLayout wf_area_2_geo[];
extern const GeoLayout wf_area_2[];
extern const Collision wf_area_2_collision[];
extern const MacroObject wf_area_2_macro_objs[];
extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern Lights1 wf_dl_f3d_material_lights;
extern Lights1 wf_dl_f3d_material_022_lights;
extern Lights1 wf_dl_f3d_material_002_lights;
extern Lights1 wf_dl_f3d_material_003_lights;
extern Lights1 wf_dl_f3d_material_007_lights;
extern Lights1 wf_dl_f3d_material_005_lights;
extern Lights1 wf_dl_f3d_material_006_lights;
extern Lights1 wf_dl_f3d_material_023_lights;
extern Vtx wf_dl_Cube_038_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_038_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_017_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_017_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_018_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_018_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_019_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_019_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_020_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_020_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_021_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_021_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_022_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_022_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_023_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_023_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_024_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_024_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_025_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_025_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_026_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_026_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_027_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_027_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_028_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_028_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_029_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_029_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_030_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_030_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_031_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_031_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_032_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_032_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_033_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_033_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_034_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_034_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_035_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_035_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_036_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_036_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_037_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_037_mesh_layer_1_tri_0[];
extern Vtx wf_dl_DeathPlane_mesh_layer_5_vtx_0[4];
extern Gfx wf_dl_DeathPlane_mesh_layer_5_tri_0[];
extern Vtx wf_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_wf_dl_f3d_material[];
extern Gfx mat_wf_dl_f3d_material_022[];
extern Gfx mat_wf_dl_f3d_material_002[];
extern Gfx mat_wf_dl_f3d_material_003[];
extern Gfx mat_wf_dl_f3d_material_007[];
extern Gfx mat_wf_dl_f3d_material_005[];
extern Gfx mat_wf_dl_f3d_material_006[];
extern Gfx mat_wf_dl_f3d_material_023[];
extern Gfx wf_dl_Cube_038_mesh_layer_1[];
extern Gfx wf_dl_Cube_017_mesh_layer_1[];
extern Gfx wf_dl_Cube_018_mesh_layer_1[];
extern Gfx wf_dl_Cube_019_mesh_layer_1[];
extern Gfx wf_dl_Cube_020_mesh_layer_1[];
extern Gfx wf_dl_Cube_021_mesh_layer_1[];
extern Gfx wf_dl_Cube_022_mesh_layer_1[];
extern Gfx wf_dl_Cube_023_mesh_layer_1[];
extern Gfx wf_dl_Cube_024_mesh_layer_1[];
extern Gfx wf_dl_Cube_025_mesh_layer_1[];
extern Gfx wf_dl_Cube_026_mesh_layer_1[];
extern Gfx wf_dl_Cube_027_mesh_layer_1[];
extern Gfx wf_dl_Cube_028_mesh_layer_1[];
extern Gfx wf_dl_Cube_029_mesh_layer_1[];
extern Gfx wf_dl_Cube_030_mesh_layer_1[];
extern Gfx wf_dl_Cube_031_mesh_layer_1[];
extern Gfx wf_dl_Cube_032_mesh_layer_1[];
extern Gfx wf_dl_Cube_033_mesh_layer_1[];
extern Gfx wf_dl_Cube_034_mesh_layer_1[];
extern Gfx wf_dl_Cube_035_mesh_layer_1[];
extern Gfx wf_dl_Cube_036_mesh_layer_1[];
extern Gfx wf_dl_Cube_037_mesh_layer_1[];
extern Gfx wf_dl_DeathPlane_mesh_layer_5[];
extern Gfx wf_dl_Cube_mesh_layer_1[];
extern Gfx wf_dl_material_revert_render_settings[];
