extern const GeoLayout bup_cube_geo[];
extern Lights1 bup_cube_f3d_material_v4_001_lights;
extern u8 bup_cube__26E73DFA_c_ci8[];
extern u8 bup_cube__26E73DFA_c_ci8_pal_rgba16[];
extern Vtx bup_cube_bup_011_mesh_layer_1_vtx_0[24];
extern Gfx bup_cube_bup_011_mesh_layer_1_tri_0[];
extern Gfx mat_bup_cube_f3d_material_v4_001[];
extern Gfx mat_revert_bup_cube_f3d_material_v4_001[];
extern Gfx bup_cube_bup_011_mesh_layer_1[];
extern Gfx bup_cube_material_revert_render_settings[];
