extern const GeoLayout fridge_geo[];
extern Lights1 fridge_X__DesignDataDigimon_Model_object_textures_obj_010_reizouko_v4_lights;
extern u8 fridge_diss_00_ci8[];
extern u8 fridge_diss_00_ci8_pal_rgba16[];
extern Vtx fridge_mesh0_mesh_layer_1_vtx_0[400];
extern Gfx fridge_mesh0_mesh_layer_1_tri_0[];
extern Gfx mat_fridge_X__DesignDataDigimon_Model_object_textures_obj_010_reizouko_v4[];
extern Gfx mat_revert_fridge_X__DesignDataDigimon_Model_object_textures_obj_010_reizouko_v4[];
extern Gfx fridge_mesh0_mesh_layer_1[];
extern Gfx fridge_material_revert_render_settings[];
