extern const GeoLayout bowling_pin_geo[];
extern Lights1 bowling_pin_f3d_material_lights;
extern Lights1 bowling_pin_f3d_material_001_lights;
extern Vtx bowling_pin_Cylinder_mesh_layer_1_vtx_0[183];
extern Gfx bowling_pin_Cylinder_mesh_layer_1_tri_0[];
extern Vtx bowling_pin_Cylinder_mesh_layer_1_vtx_1[20];
extern Gfx bowling_pin_Cylinder_mesh_layer_1_tri_1[];
extern Gfx mat_bowling_pin_f3d_material[];
extern Gfx mat_bowling_pin_f3d_material_001[];
extern Gfx bowling_pin_Cylinder_mesh_layer_1[];
extern Gfx bowling_pin_material_revert_render_settings[];
