extern const GeoLayout ddd_area_1_geo[];
extern const GeoLayout ddd_area_1[];
extern const Collision ddd_area_1_collision[];
extern const MacroObject ddd_area_1_macro_objs[];
extern const GeoLayout ddd_area_2_geo[];
extern const GeoLayout ddd_area_2[];
extern const Collision ddd_area_2_collision[];
extern const MacroObject ddd_area_2_macro_objs[];
extern Lights1 ddd_dl_f3d_material_lights;
extern Vtx ddd_dl_Cylinder_mesh_layer_1_vtx_0[206];
extern Gfx ddd_dl_Cylinder_mesh_layer_1_tri_0[];
extern Vtx ddd_dl_DeathPlane_mesh_layer_5_vtx_0[4];
extern Gfx ddd_dl_DeathPlane_mesh_layer_5_tri_0[];
extern Vtx ddd_dl_Cylinder_001_mesh_layer_1_vtx_0[206];
extern Gfx ddd_dl_Cylinder_001_mesh_layer_1_tri_0[];
extern Vtx ddd_dl_DeathPlane_001_mesh_layer_5_vtx_0[4];
extern Gfx ddd_dl_DeathPlane_001_mesh_layer_5_tri_0[];
extern Gfx mat_ddd_dl_f3d_material[];
extern Gfx mat_ddd_dl_f3d_material_008[];
extern Gfx ddd_dl_Cylinder_mesh_layer_1[];
extern Gfx ddd_dl_DeathPlane_mesh_layer_5[];
extern Gfx ddd_dl_Cylinder_001_mesh_layer_1[];
extern Gfx ddd_dl_DeathPlane_001_mesh_layer_5[];
extern Gfx ddd_dl_material_revert_render_settings[];
